### ISSUE TITLE
Image drop/upload doesn't work

### ISSUE THREAD

**Issue by mkostera** [irislib/iris-client#6]
It shows me 
"No url received from https://nostr.build/api/v2/upload/files"
again and again from yesterday. Tried on Brave, LibreWolf and Firefox.

**Comment by mmalmi** [comment]
Nostr.build now requires login to upload 😞

**Comment by mmalmi** [comment]
Should probably change to https://void.cat/ which supports blossom as well

**Comment by mmalmi** [comment]
Snort.social adds authorization header and it works. We should do the same — or use blossom for uploads.

**Comment by mmalmi** [comment]
Added nip-96 endpoint & authorization header. Should work again.
